// <auto-generated />
using System;
using GastronomePlatform.Modules.Media.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GastronomePlatform.Modules.Media.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GastronomePlatform.Modules.Media.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataCategory")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_MediaFiles_HardDeleteCandidates")
                        .HasFilter("\"Status\" = 4");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_MediaFiles_OwnerUserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_MediaFiles_EntityType_EntityId");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_MediaFiles_OrphanCleanup")
                        .HasFilter("\"EntityType\" IS NULL");

                    b.ToTable("MediaFiles", "media", t =>
                        {
                            t.HasCheckConstraint("CK_MediaFiles_DimensionsBothOrNone", "(\"Width\" IS NULL AND \"Height\" IS NULL) OR (\"Width\" IS NOT NULL AND \"Height\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MediaFiles_EntityRefsMatchNullity", "(\"EntityType\" IS NULL AND \"EntityId\" IS NULL) OR (\"EntityType\" IS NOT NULL AND \"EntityId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MediaFiles_PersonalRequiresOwner", "\"DataCategory\" <> 1 OR \"OwnerUserId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_MediaFiles_SizeBytesPositive", "\"SizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Media.Domain.Entities.MediaThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId", "Size", "Format")
                        .IsUnique()
                        .HasDatabaseName("UX_MediaThumbnails_File_Size_Format");

                    b.ToTable("MediaThumbnails", "media", t =>
                        {
                            t.HasCheckConstraint("CK_MediaThumbnails_DimensionsPositive", "\"Width\" > 0 AND \"Height\" > 0");

                            t.HasCheckConstraint("CK_MediaThumbnails_SizeBytesPositive", "\"SizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Media.Domain.Entities.MediaThumbnail", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Media.Domain.Entities.MediaFile", null)
                        .WithMany("Thumbnails")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Media.Domain.Entities.MediaFile", b =>
                {
                    b.Navigation("Thumbnails");
                });
#pragma warning restore 612, 618
        }
    }
}
