// <auto-generated />
using System;
using GastronomePlatform.Modules.Subscriptions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GastronomePlatform.Modules.Subscriptions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    partial class SubscriptionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("subscriptions")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanGrant", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grant")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "Grant");

                    b.ToTable("PlanGrants", "subscriptions");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AvailableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CompareAtAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FallbackPriceId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPurchasable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RenewsAsPriceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TrialDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FallbackPriceId");

                    b.HasIndex("RenewsAsPriceId");

                    b.HasIndex("PlanId", "IsActive");

                    b.ToTable("PlanPrices", "subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_PlanPrices_AmountNonNegative", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_PlanPrices_AvailabilityWindow", "\"AvailableFrom\" IS NULL OR \"AvailableUntil\" IS NULL OR \"AvailableFrom\" < \"AvailableUntil\"");

                            t.HasCheckConstraint("CK_PlanPrices_TrialRequiresFreeWithDays", "\"Kind\" <> 0 OR (\"Amount\" = 0 AND \"TrialDays\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Promotions", "subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Promotions_PeriodOrdered", "\"From\" < \"To\"");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PromotionGrant", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grant")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGrant")
                        .HasColumnType("boolean");

                    b.HasKey("PromotionId", "Grant");

                    b.ToTable("PromotionGrants", "subscriptions");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PromotionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId", "TargetType", "TargetValue")
                        .IsUnique();

                    b.ToTable("PromotionTargets", "subscriptions");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TermsSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "Version")
                        .IsUnique();

                    b.ToTable("SubscriptionAgreements", "subscriptions");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GatewayPayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GatewayTransactionId")
                        .IsUnique()
                        .HasFilter("\"GatewayTransactionId\" IS NOT NULL");

                    b.HasIndex("PriceId");

                    b.HasIndex("SubscriptionId", "OccurredAt");

                    b.ToTable("SubscriptionPayments", "subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionPayments_AmountNonNegative", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AvailableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("PlanKind")
                        .HasColumnType("integer");

                    b.Property<string>("PublicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequiredRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TechnicalName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalName")
                        .IsUnique()
                        .HasFilter("\"TechnicalName\" IS NOT NULL");

                    b.ToTable("SubscriptionPlans", "subscriptions");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentPriceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("GatewayPaymentMethodId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("NextBillingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RecurringDisabledReason")
                        .HasColumnType("integer");

                    b.Property<decimal>("SnapshotAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SnapshotCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TrialEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPriceId");

                    b.HasIndex("NextBillingAt");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserSubscriptions", "subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_UserSubscriptions_CurrentPeriodOrdered", "\"CurrentPeriodStart\" < \"CurrentPeriodEnd\"");

                            t.HasCheckConstraint("CK_UserSubscriptions_FailedAttemptsNonNegative", "\"FailedAttempts\" >= 0");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanGrant", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPlan", null)
                        .WithMany("Grants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanPrice", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanPrice", null)
                        .WithMany()
                        .HasForeignKey("FallbackPriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanPrice", null)
                        .WithMany()
                        .HasForeignKey("RenewsAsPriceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PromotionGrant", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PromotionTarget", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionAgreement", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.UserSubscription", null)
                        .WithMany("Agreements")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanPrice", null)
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.UserSubscription", null)
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.PlanPrice", null)
                        .WithMany()
                        .HasForeignKey("CurrentPriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Grants");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Subscriptions.Domain.Entities.UserSubscription", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
