// <auto-generated />
using System;
using GastronomePlatform.Modules.Dishes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GastronomePlatform.Modules.Dishes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DishesDbContext))]
    [Migration("20260614094013_AddTagSlug")]
    partial class AddTagSlug
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dishes")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IconMediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllergensMask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CostEstimate")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DietLabelsMask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("FavoritesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("HasUnverifiedAllergens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("HistoryText")
                        .HasColumnType("text");

                    b.Property<Guid?>("MainImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModerationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedVersionData")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedVersionUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ViewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Dishes", "dishes", t =>
                        {
                            t.HasCheckConstraint("CK_Dishes_FavoritesCountNonNegative", "\"FavoritesCount\" >= 0");

                            t.HasCheckConstraint("CK_Dishes_RatingAvgRange", "\"RatingAvg\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_Dishes_RatingCountNonNegative", "\"RatingCount\" >= 0");

                            t.HasCheckConstraint("CK_Dishes_ViewsCountNonNegative", "\"ViewsCount\" >= 0");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishCategory", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("DishId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DishCategories", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishCategoryPublished", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("DishId", "CategoryId");

                    b.HasIndex("CategoryId", "DishId");

                    b.ToTable("DishCategoriesPublished", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishTag", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("DishId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DishTags", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishTagPublished", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("DishId", "TagId");

                    b.HasIndex("TagId", "DishId");

                    b.ToTable("DishTagsPublished", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AllergenType")
                        .HasColumnType("integer");

                    b.Property<Guid>("BaseMeasureUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultNutritionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DensityApprox")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DietConflictsMask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ImageMediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAllergen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLiquid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PluralName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BaseMeasureUnitId");

                    b.HasIndex("DefaultNutritionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients", "dishes", t =>
                        {
                            t.HasCheckConstraint("CK_Ingredients_AllergenType", "\"IsAllergen\" = false OR \"AllergenType\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Ingredients_LiquidDensity", "\"IsLiquid\" = false OR \"DensityApprox\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.IngredientSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NutritionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("NutritionId")
                        .IsUnique();

                    b.ToTable("IngredientSpecs", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.MeasureUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ConversionToBase")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MeasureUnits", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Nutrition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalcMethod")
                        .HasColumnType("integer");

                    b.Property<decimal>("Calories")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("Fats")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("Fiber")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("Proteins")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("Salt")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("SaturatedFats")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("Sugar")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Nutritions", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorTips")
                        .HasColumnType("text");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntroductionText")
                        .HasColumnType("text");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("NutritionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServingSuggestions")
                        .HasColumnType("text");

                    b.Property<int>("ServingsDefault")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishId")
                        .IsUnique();

                    b.HasIndex("NutritionId")
                        .IsUnique();

                    b.ToTable("Recipes", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FreeformText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IngredientSpecId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeasureUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PreparationNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("IngredientSpecId");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("RecipeId", "Order")
                        .IsUnique();

                    b.ToTable("RecipeIngredients", "dishes", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeIngredients_IngredientXorFreeform", "(\"IngredientId\" IS NOT NULL AND \"FreeformText\" IS NULL) OR (\"IngredientId\" IS NULL AND \"FreeformText\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_RecipeIngredients_OrderPositive", "\"Order\" > 0");

                            t.HasCheckConstraint("CK_RecipeIngredients_QuantityPositive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_RecipeIngredients_SpecRequiresIngredient", "\"IngredientSpecId\" IS NULL OR \"IngredientId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageMediaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TemperatureCelsius")
                        .HasColumnType("integer");

                    b.Property<int?>("TimerMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Order")
                        .IsUnique();

                    b.ToTable("RecipeSteps", "dishes", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeSteps_OrderPositive", "\"Order\" > 0");

                            t.HasCheckConstraint("CK_RecipeSteps_TemperatureRange", "\"TemperatureCelsius\" IS NULL OR (\"TemperatureCelsius\" BETWEEN -30 AND 300)");

                            t.HasCheckConstraint("CK_RecipeSteps_TimerRange", "\"TimerMinutes\" IS NULL OR (\"TimerMinutes\" BETWEEN 1 AND 1440)");
                        });
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Timing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTotalManual")
                        .HasColumnType("boolean");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RestTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("Timings", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Yield", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GramsPerServing")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<decimal>("QuantityTotal")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("ServingsCount")
                        .HasColumnType("integer");

                    b.Property<int>("YieldUnit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("Yields", "dishes");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Category", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishCategory", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", null)
                        .WithMany("Categories")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishCategoryPublished", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", null)
                        .WithMany("CategoriesPublished")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishTag", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", null)
                        .WithMany("Tags")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.DishTagPublished", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", null)
                        .WithMany("TagsPublished")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.MeasureUnit", null)
                        .WithMany()
                        .HasForeignKey("BaseMeasureUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Nutrition", null)
                        .WithMany()
                        .HasForeignKey("DefaultNutritionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.IngredientSpec", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Nutrition", null)
                        .WithMany()
                        .HasForeignKey("NutritionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", null)
                        .WithOne("Recipe")
                        .HasForeignKey("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", "DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Nutrition", "Nutrition")
                        .WithMany()
                        .HasForeignKey("NutritionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.IngredientSpec", null)
                        .WithMany()
                        .HasForeignKey("IngredientSpecId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.MeasureUnit", null)
                        .WithMany()
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.RecipeStep", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Timing", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", null)
                        .WithOne("Timing")
                        .HasForeignKey("GastronomePlatform.Modules.Dishes.Domain.Entities.Timing", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Yield", b =>
                {
                    b.HasOne("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", null)
                        .WithOne("Yield")
                        .HasForeignKey("GastronomePlatform.Modules.Dishes.Domain.Entities.Yield", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Dish", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CategoriesPublished");

                    b.Navigation("Recipe")
                        .IsRequired();

                    b.Navigation("Tags");

                    b.Navigation("TagsPublished");
                });

            modelBuilder.Entity("GastronomePlatform.Modules.Dishes.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Timing")
                        .IsRequired();

                    b.Navigation("Yield")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
